Update build-and-push-docker-image.yml

diff --git a/.github/workflows/build-and-push-docker-image.yml b/.github/workflows/build-and-push-docker-image.yml
--- a/.github/workflows/build-and-push-docker-image.yml
+++ b/.github/workflows/build-and-push-docker-image.yml
@@ -31,8 +31,60 @@ on:
         required: false
 
 jobs:
+  get-base-image-info:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Install Skopeo (if not already present)
+        run: sudo apt-get update && sudo apt-get install -y skopeo
+
+      - name: Set up image tag (lowercase)
+        id: vars
+        run: |
+          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
+          REPO_NAME=$(echo "${REPO_LOWER}"|awk -F'/' '{print $2}')
+          echo "tag=ghcr.io/${REPO_LOWER}:${{ inputs.dockertag }}" >> $GITHUB_OUTPUT
+          echo "repo_name=${REPO_NAME}" >> $GITHUB_OUTPUT
+          # recupero l'immagine di base dal Dockerfile
+          BASE_IMAGE="$(cat ${{ inputs.dockerfile }}|grep ^FROM|awk '{print $2}')"
+          echo "base_image=${BASE_IMAGE}" >> $GITHUB_OUTPUT
+
+      - name: Get Base Image Digest
+        id: get_digest
+        run: |
+          FULL_BASE_IMAGE="${{ steps.vars.tag }}"
+
+          echo "Inspecting base image: $FULL_BASE_IMAGE"
+
+          # Ottieni il manifest completo dell'immagine base
+          # Reindirizza stderr a stdout per catturare gli errori nell'output
+          # se è un'immagine ufficiale bisogna aggiungere "docker.io/library"
+          MANIFEST_OUTPUT=$(skopeo inspect docker://"$FULL_BASE_IMAGE" 2>&1)
+
+          PARSED_DIGEST=$(echo "$MANIFEST_OUTPUT" | jq -r '.Digest' 2>/dev/null)
+
+          if [ -z "$PARSED_DIGEST" ] || [ "$PARSED_DIGEST" == "null" ]; then
+              echo "::error::Failed to get valid digest for base image: $FULL_BASE_IMAGE"
+              echo "::error::Raw output of 'docker manifest inspect $FULL_BASE_IMAGE':"
+              echo "$MANIFEST_OUTPUT"
+              exit 1
+          fi
+
+          echo "Base Image Name: $FULL_BASE_IMAGE"
+          echo "Base Image Digest: $PARSED_DIGEST"
+          echo "base_image_name=$FULL_BASE_IMAGE" >> "$GITHUB_OUTPUT"
+          echo "base_image_digest=$PARSED_DIGEST" >> "$GITHUB_OUTPUT"
+        shell: bash
+    outputs:
+      base_image_name: ${{ steps.get_digest.outputs.base_image_name }}
+      base_image_digest: ${{ steps.get_digest.outputs.base_image_digest }}
+      image_tag: ${{ steps.var.outputs.tag }}
+
   build-and-push:
     runs-on: ubuntu-latest
+    needs: get-base-image-info
     permissions:
       contents: read # Permesso per il checkout del codice
       packages: write # Permesso per scrivere pacchetti (necessario per GHCR)
@@ -48,28 +100,17 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Set up image tag (lowercase)
-        id: vars
-        run: |
-          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
-          REPO_NAME=$(echo "${REPO_LOWER}"|awk -F'/' '{print $2}')
-          echo "tag=ghcr.io/${REPO_LOWER}:${{ inputs.dockertag }}" >> $GITHUB_OUTPUT
-          echo "repo_name=${REPO_NAME}" >> $GITHUB_OUTPUT
-          # recupero l'immagine di base dal Dockerfile
-          BASE_IMAGE="$(cat ${{ inputs.dockerfile }}|grep ^FROM|awk '{print $2}')"
-          echo "base_image=${BASE_IMAGE}" >> $GITHUB_OUTPUT
-
       - name: Build Docker image
         run: |
-          docker build --pull --label "org.opencontainers.image.base.digest=${{ inputs.base_image_digest }}" \
-          --label "org.opencontainers.image.base=${{ steps.vars.outputs.base_image }}" \
-          -t ${{ steps.vars.outputs.tag }} -f ${{ inputs.dockerdir }}/${{ inputs.dockerfile }} ${{ inputs.dockerdir }}/
+          docker build --pull --label "org.opencontainers.image.base.digest=${{ needs.get-base-image-info.base_image_digest }}" \
+          --label "org.opencontainers.image.base=${{ needs.get-base-image-info.base_image_name }}" \
+          -t ${{ needs.get-base-image-info.image_tag }} -f ${{ inputs.dockerdir }}/${{ inputs.dockerfile }} ${{ inputs.dockerdir }}/
             
       - name: Push Docker image to GHCR
-        run: docker push ${{ steps.vars.outputs.tag }}
+        run: docker push ${{ needs.get-base-image-info.image_tag }}
 
       - name: Set INPUT_IMAGE_REF
-        run: echo "INPUT_IMAGE_REF=${{ steps.vars.outputs.tag }}" >> $GITHUB_ENV
+        run: echo "INPUT_IMAGE_REF=${{ needs.get-base-image-info.image_tag }}" >> $GITHUB_ENV
 
 #  get-base-image-info:
 #    secrets: inherit
