Update check-docker-image-update.yml

diff --git a/.github/workflows/check-docker-image-update.yml b/.github/workflows/check-docker-image-update.yml
--- a/.github/workflows/check-docker-image-update.yml
+++ b/.github/workflows/check-docker-image-update.yml
@@ -11,7 +11,7 @@ on:
         required: true
         type: string
       dockertag:
-        description: 'Tag for the image (eg: 24.04 or empty for latest)'
+        description: 'Tags for the image separated by comma (eg: 24.04,22.04 or empty for latest)'
         required: false
         type: string
         default: "latest"
@@ -23,11 +23,11 @@ on:
   workflow_call: # Permette di riutilizzare il workflow da un altro repo
     inputs:
       image_repo:
-        description: 'Repo for the image'
+        description: 'Repo for the image (eg: neomediatech/ubuntu-base)'
         required: true
         type: string
       dockertag:
-        description: 'Tag for the image'
+        description: 'Tags for the image separated by comma (eg: 24.04,22.04 or empty for latest)'
         required: false
         type: string
         default: "latest"
@@ -41,6 +41,39 @@ on:
         value: ${{ jobs.check.outputs.needs-updating }}
 
 jobs:
+  generate_matrix:
+    runs-on: ubuntu-latest
+    outputs:
+      versions: ${{ steps.set_versions.outputs.versions }}
+    steps:
+      - name: Set Versions for Matrix
+        id: set_versions
+        run: |
+          set -euo pipefail # Fail immediately if any command fails or variable is unset
+
+          # Check if jq is available (it should be on ubuntu-latest)
+          if ! command -v jq &> /dev/null
+          then
+              echo "Error: jq is not installed. It is required for this step."
+              exit 1
+          fi
+
+          INPUT_VERSIONS=$(printf "%s" "${{ inputs.dockertag }}" | tr -d '\n' | xargs)
+
+          if [ -z "$INPUT_VERSIONS" ]; then
+            SELECTED_VERSIONS="$VERSIONS"
+            echo "Building all versions: $SELECTED_VERSIONS"
+          else
+            SELECTED_VERSIONS="$INPUT_VERSIONS"
+            echo "Building selected versions: $SELECTED_VERSIONS"
+          fi
+
+          # Converte la stringa separata da virgole in un array JSON
+          JSON_VERSIONS=$(jq -c -R -s 'split(",") | map(select(length > 0) | gsub("\\n"; ""))' <<< "$SELECTED_VERSIONS")
+
+          printf "versions=%s\n" "$JSON_VERSIONS" >> "$GITHUB_OUTPUT"
+        shell: bash
+
   check:
     runs-on: ubuntu-latest
     permissions:
