Update cron-check-docker-images.yml

diff --git a/.github/workflows/cron-check-docker-images.yml b/.github/workflows/cron-check-docker-images.yml
--- a/.github/workflows/cron-check-docker-images.yml
+++ b/.github/workflows/cron-check-docker-images.yml
@@ -20,7 +20,7 @@ jobs:
           echo "IMAGES: $IMAGES"
           MATRIX_JSON="{\"images\":[${IMAGES}]}"
           echo "matrix=${MATRIX_JSON}"
-          echo "matrix=${MATRIX_JSON}" >> $GITHUB_OUTPUT
+          echo "matrix=${MATRIX_JSON}" >> "$GITHUB_OUTPUT"
 
   update-check:
     runs-on: [self-hosted]
@@ -32,26 +32,38 @@ jobs:
         id: check-update
         run: |
           echo "The current value from the matrix is ${{ matrix.images }}"
-          #IMAGE_META="$(skopeo inspect docker://${{ matrix.images }} || echo "")"
-          #IMAGE_BASE="$(echo $IMAGE_META | jq -r '.Labels."org.opencontainers.image.base"' || echo "")"
-          #IMAGE_BASE_DIGEST="$(echo $IMAGE_META | jq -r '.Labels."org.opencontainers.image.base.digest"' || echo "")"
-          #CURRENT_IMAGE_BASE_DIGEST="$(skopeo inspect docker://$IMAGE_BASE | jq -r '.Digest' || echo "")"
+          IMAGE_META="$(skopeo inspect docker://${{ matrix.images }} || echo "")"
+          IMAGE_BASE="$(echo $IMAGE_META | jq -r '.Labels."org.opencontainers.image.base"' || echo "")"
+          IMAGE_BASE_DIGEST="$(echo $IMAGE_META | jq -r '.Labels."org.opencontainers.image.base.digest"' || echo "")"
+          CURRENT_IMAGE_BASE_DIGEST="$(skopeo inspect docker://$IMAGE_BASE | jq -r '.Digest' || echo "")"
 
-          #echo "IMAGE_BASE=$IMAGE_BASE"
-          #echo "IMAGE_BASE_DIGEST=$IMAGE_BASE_DIGEST"
-          #echo "CURRENT_IMAGE_BASE_DIGEST=$CURRENT_IMAGE_BASE_DIGEST"
+          echo "IMAGE_BASE=$IMAGE_BASE"
+          echo "IMAGE_BASE_DIGEST=$IMAGE_BASE_DIGEST"
+          echo "CURRENT_IMAGE_BASE_DIGEST=$CURRENT_IMAGE_BASE_DIGEST"
 
-          #if [[ "$IMAGE_BASE_DIGEST" == "" || "$CURRENT_IMAGE_BASE_DIGEST" == "" ]]; then
-          #  echo "::warning:: Digest not found"
-          #  RES="❌ digest non found"
-          #elif [[ "$IMAGE_BASE_DIGEST" != "$CURRENT_IMAGE_BASE_DIGEST" ]]; then
-          #  echo "::notice:: Image needs update"
-          #  RES="⚠️🔁 update needed"
-          #else
-          #  echo "::notice:: Update not needed"
-          #  RES="✅ update NOT needed"
-          #fi
-          RES=$RANDOM
+          GLOBAL_STATUS=""
+          ICON_TITLE=""
+          if [[ "$IMAGE_BASE_DIGEST" == "" || "$CURRENT_IMAGE_BASE_DIGEST" == "" ]]; then
+            echo "::warning:: Digest not found"
+            RES="❌ digest non found"
+            GLOBAL_STATUS="ERROR"
+            ICON_TITLE="❌"
+          elif [[ "$IMAGE_BASE_DIGEST" != "$CURRENT_IMAGE_BASE_DIGEST" ]]; then
+            echo "::notice:: Image update required"
+            RES="⚠️🔁 update required"
+            if [[ "$GLOBAL_STATUS" != "ERROR" ]]; then
+              GLOBAL_STATUS="UPDATE_REQUIRED"
+              ICON_TITLE="🔁"
+            fi
+          else
+            echo "::notice:: Update not required"
+            RES="✅ update NOT required"
+            if [[ "$GLOBAL_STATUS" == "" ]]; then
+              GLOBAL_STATUS="UPDATE_OK"
+              ICON_TITLE="✅"
+            fi
+          fi
+          #RES=$RANDOM
           echo "::notice:: ${{ matrix.images }} $RES"
           echo "${{ matrix.images }} $RES" > result.txt
 
@@ -70,6 +82,7 @@ jobs:
       - name: Set some var
         run: |
           echo "REPORT_NAME=image-update-report-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}" >> $GITHUB_ENV
+          echo "REPORT_DATE=$(TZ="Europe/Rome" date) >> $GITHUB_ENV
 
       - name: Download all artifacts
         uses: actions/download-artifact@v4
@@ -80,6 +93,17 @@ jobs:
         run: |
           echo "--- Riassunto risultati ---"
           cat results/*/result.txt |sort > all-results.txt
+          if grep -q "❌" all-results.txt; then
+            ICON_TITLE="❌"
+          elif grep -q "🔁" all-results.txt; then
+            ICON_TITLE="🔁"
+          elif grep -q "✅" all-results.txt; then
+            ICON_TITLE="✅"
+          else
+            ICON_TITLE=""
+          fi
+
+          echo "ICON_TITLE=$ICON_TITLE" >> $GITHUB_ENV
 
       - name: Upload global report
         uses: actions/upload-artifact@v4
@@ -94,7 +118,8 @@ jobs:
         uses: Neomediatech/gh-workflows/.github/actions/send-notification@main
         with:
           report-name: ${{ env.REPORT_NAME }}
-          #message: "un messaggio"
+          title: "${{ env.ICON_TITLE }} Aggiornamenti immagini docker BASE"
+          message: "${{ env.REPORT_DATE }}"
           notify-cmd: ${{ secrets.NOTIFY_CMD }}
           notify-up: ${{ secrets.NOTIFY_UP }}
           notify-endpoint: ${{ secrets.NOTIFY_ENDPOINT }}
